- hosts: all
  vars:
    server_url: "http://172.16.244.150:9000/zabbix/"
  tasks:
  - name: Get zabbix host group Info
    register: group_info
    local_action:
      module: zabbix_group_info
      server_url: "{{ server_url }}"
      login_user: admin
      login_password: zabbix
      timeout: 10
      hostgroup_name: "Gavin_TEST"

  - name: get group result
    debug:
      msg: "{{ group_info }}"
